#' Run Crosstalk Inference Pipeline
#'
#' Integrates pathway enrichment results, expression data, and a background interaction
#' network to infer pathway–pathway (or TF–pathway) crosstalk using mutual information (MI)
#' and permutation testing.
#'
#' @param enrichment_df A `data.frame` describing enriched terms and their member genes
#'   (e.g., output from [enrich_path()] or a compatible table). The first column must
#'   contain term/pathway identifiers and the second column must contain gene members
#'   as a single character string separated by commas (`,` ) or slashes (`/`), as expected
#'   by [prepare_sets()].
#'
#' @param expr A numeric matrix or `data.frame` of expression-like values with **genes as rows**
#'   and **samples as columns**. Gene identifiers must be in `rownames(expr)`.
#'
#' @param group_names Optional character vector of patterns used to define sample groups
#'   by matching against `colnames(expr)` (e.g., `c("Normal", "Tumor")`). Passed to
#'   [prepare_data()] for group-aware processing.
#'
#' @param iter Integer. Number of permutations used to generate the null distribution
#'   for the crosstalk statistic. Default is `100`.
#'
#' @param convert.ID Optional. If not `NULL`, triggers gene ID conversion in
#'   [prepare_data()] via [map_me()].
#'
#' @param species Optional character. Species identifier passed to [prepare_data()]
#'   (and ultimately to [map_me()]) for gene ID mapping.
#'
#' @param mapping_file Optional. Reserved for custom ID mapping files. Currently not
#'   used inside `crosstalk()`.
#'
#' @param net Optional edge-list `data.frame` defining a background interaction network.
#'   If `NULL`, [retrieve_net()] loads the default network bundled with the package.
#'   The network must contain at least two columns representing edge endpoints; additional
#'   columns (e.g., `mor`) are allowed.
#'
#' @param prefix Character. Prefix used to name outputs generated by
#'   [compute_crosstalk()]. Default is `"res"`.
#'
#' @param ... Additional arguments (currently unused). Reserved for future extensions.
#'
#' @details
#' The pipeline performs the following steps:
#' \enumerate{
#'   \item Constructs gene sets from `enrichment_df` using [prepare_sets()].
#'   \item Preprocesses expression data and computes per-gene z-scores using [prepare_data()].
#'   \item Loads or constructs a background interaction network via [retrieve_net()].
#'   \item Computes mutual information (MI) for network edges using [compute_mi()].
#'   \item Estimates pathway crosstalk statistics and permutation-based p-values
#'   using [compute_crosstalk()].
#' }
#'
#' Progress messages and total runtime (in seconds) are printed during execution.
#'
#' @return A `data.frame` of pairwise gene-set interactions as returned by
#'   [compute_crosstalk()]. The output typically includes observed interaction degree,
#'   MI-based scores (e.g., `mi_score`, `mi_norm`), overlap metrics (e.g., Jaccard index),
#'   and permutation-derived p-values.
#'
#' @seealso [prepare_sets()], [prepare_data()], [retrieve_net()],
#'   [compute_mi()], [compute_crosstalk()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' res <- crosstalk(enrichment_df, expr,
#'                  group_names = c("Normal", "Tumor"),
#'                  iter = 100)
#' head(res)
#' }

crosstalk <- function(enrichment_df, expr, group_names = NULL, iter = 100,
                          convert.ID = NULL, species = NULL, mapping_file = NULL,
                          net = NULL, prefix= "res",
                          ...) {

          start_time <- Sys.time()
          #  Prepare pathway gene lists
          gset_list= prepare_sets(enrichment_df, expr)
          genes= unlist(gset_list) |> unique()
          message("Pathway list prepared with ", length(gset_list), " pathways.")

          # Prepare expression data
          z_score <- prepare_data(expr, group_names, genes,  z_norm = TRUE,  convert.ID = convert.ID, species= species)
          message("Expression data processed.")

          #Construct background network
          net <- retrieve_net(net)
          message("Background interaction network constructed.")

          # Compute mutual information
          mi_df <- compute_mi(z_score, net)
          message("Mutual information matrix computed.")

          #  Run crosstalk algorithm
          result <- compute_crosstalk(gset_list, mi_df, iter, prefix)
          message("crosstalk analysis completed.")
          end_time <- Sys.time()
          runtime <- as.numeric(difftime(end_time, start_time, units = "secs"))
          print(paste0("Total Run Time: ", round(runtime, 2), " sec"))

          return(result)
}
